# Generated by Django 5.2.3 on 2025-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tags', '0003_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
